"""Integration tests for AWL Expose: with real API calls.

Reproduces the failure documented in reports/expose-tool-failure-analysis.md:
when a task must expose complex values extracted from a report, the model
describes them in prose but omits the required JSON block.
"""

import os

import pytest

from ai_assist.awl_ast import IfNode, TaskNode, WorkflowNode
from ai_assist.awl_runtime import AWLRuntime, RuntimeLimits

pytestmark = pytest.mark.integration

HAVE_API_ACCESS = bool(os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_VERTEX_PROJECT_ID"))
skip_no_api = pytest.mark.skipif(
    not HAVE_API_ACCESS, reason="No API access (set ANTHROPIC_API_KEY or ANTHROPIC_VERTEX_PROJECT_ID)"
)

# Real PR analysis report that triggered the expose failure in production.
# Contains === SECTION === markers with complex multi-paragraph content
# including YAML code blocks, tables, and cross-references.
COMPLEX_REPORT = """\
<!-- Generated by AI Assistant -->

# PR Analysis — distributedci/dci-openshift-app-agent#18

**PR:** [Resolve must-gather short names before log collection](https://github.com/distributedci/dci-openshift-app-agent/pull/18)
**Jira:** [CILAB-2663](https://redhat.atlassian.net/browse/CILAB-2663) — Support version-independent must-gather image names in pipeline files
**Branch:** `resolve-must-gather-images` → `main`
**State:** open, not draft

---

## Current State

The PR currently adds `redhatci.ocp.resolve_must_gather_images` role call only in `plays/dump_ocp_logs.yml` (log collection phase). It does **NOT** resolve short names before mirroring in `plays/pre-run.yml`.

**Changed files (current diff):**
- `plays/dump_ocp_logs.yml`: +8 lines — adds resolve role before must-gather log collection

**Missing:**
- `plays/pre-run.yml`: resolve role must be added BEFORE the `mirror_images` role call (lines 83-93) for disconnected environments.

---

=== FIX PLAN ===

### 1. change_request — Add resolve before mirror in `plays/pre-run.yml` [REQUIRED]

**Source:** Human reviewer comment (Jul 19 10:04):
> "The DCI failed job is because the mirroring phase doesn't have the correct names for the must_gather images so it must be fixed in this change to resolve the names before the mirroring."

**Fix:** Insert the following block in `plays/pre-run.yml` BEFORE the "Mirror must gather images" task (currently at line 83):

```yaml
- name: Resolve must-gather short names to full image references
  ansible.builtin.include_role:
    name: redhatci.ocp.resolve_must_gather_images
  vars:
    rmgi_images: >-
      {{ dci_must_gather_images |
        default(['registry.redhat.io/openshift4/ose-must-gather']) }}
  when:
    - dci_disconnected | default(false) | bool
    - dci_local_registry | length
    - do_must_gather | bool
```

The `when:` conditions match the existing `mirror_images` task so the resolve step only runs in disconnected environments when must-gather is enabled.

### 2. DCI CI failure — job 2883ae27 [FIXED BY #1]

- **Root cause (RCA):** Task ordering — `mirror_images` runs before `resolve_must_gather_images` in pre-run phase
- **Fix:** Code change in #1 above
- **Note:** This is a code bug, NOT an infrastructure issue.

### 3. Zuul dci/check: SUCCESS

No action needed. Zuul checks pass on the current commit.

---

=== COMMENTS SUMMARY ===

| # | Author | Date | Classification | Summary |
|---|--------|------|----------------|---------|
| 1 | fredericlepied | Jul 18 23:10 | IGNORED | "recheck" — CI trigger command |
| 2 | dcibot | Jul 19 08:12 | ci_failure | ERROR job bc5db990 from samsung-ran-lab-config#329 |
| 3 | fredericlepied | Jul 19 09:57 | informational | Agent status update — incorrectly concluded "infra issue" |
| 4 | fredericlepied | Jul 19 10:04 | **change_request** | Human correction: mirroring fails because short names not resolved before mirror phase — fix pre-run.yml |
| 5 | dcibot | Jul 20 19:56 | ci_failure | ERROR job 2883ae27 from samsung-ran-lab-config#329 (same root cause) |
| 6 | fredericlepied | Jul 21 07:50 | informational | Agent status update — notes scope is only dump_ocp_logs.yml |

**No inline (code-level) PR review comments found.**

---

=== COMPANION REPOS ===

[]

(All companion repos are already tracked in the triage list:
- `redhatci/ansible-collection-redhatci-ocp` → PR #986 (external, not managed here)
- `distributedci/dci-openshift-agent` → PR #101 (handled in its own iteration))

---

=== NEEDS CODE CHANGES ===

true

---

## Technical Details

### `plays/pre-run.yml` current state (lines 83-93)

```yaml
- name: Mirror must gather images
  ansible.builtin.include_role:
    name: redhatci.ocp.mirror_images
  vars:
    mi_images: "{{ dci_must_gather_images | default(['registry.redhat.io/openshift4/ose-must-gather']) }}"
    mi_authfile: "{{ pullsecret_tmp_file }}"
    mi_registry: "{{ dci_local_registry }}"
  when:
    - dci_disconnected | default(false) | bool
    - dci_local_registry | length
    - do_must_gather | bool
```

The resolve task must be inserted immediately before this block.

### RCA Summary for job 2883ae27

- **Failing task:** "Mirror must gather images" at 19:54:17 UTC
- **Error:** `skopeo copy docker://ose-must-gather:latest in docker.io/library/ose-must-gather: requested access to the resource is denied`
- **Root cause:** Short name `ose-must-gather` passed directly to `skopeo`, which resolves it to `docker.io/library/` (non-existent).
- **Fix confidence:** HIGH — direct log evidence at every causal level.
"""


@pytest.fixture
async def real_agent(tmp_path):
    """Create a real agent with API access and minimal tools.

    Supports both direct API (ANTHROPIC_API_KEY) and Vertex AI
    (ANTHROPIC_VERTEX_PROJECT_ID + ANTHROPIC_VERTEX_REGION).
    """
    from ai_assist.agent import AiAssistAgent
    from ai_assist.config import AiAssistConfig

    config = AiAssistConfig(
        anthropic_api_key=os.environ.get("ANTHROPIC_API_KEY", ""),
        vertex_project_id=os.environ.get("ANTHROPIC_VERTEX_PROJECT_ID"),
        vertex_region=os.environ.get("ANTHROPIC_VERTEX_REGION"),
        model="claude-sonnet-4-6",
        mcp_servers={},
    )
    agent = AiAssistAgent(config)
    await agent.connect_to_servers()

    # Pre-create a report file the agent can read (reports dir created by conftest)
    reports_dir = agent.report_tools.reports_dir
    reports_dir.mkdir(parents=True, exist_ok=True)
    (reports_dir / "pr-analysis-247.md").write_text(COMPLEX_REPORT)

    yield agent


@skip_no_api
@pytest.mark.asyncio
async def test_expose_complex_values_from_report(real_agent, capsys):
    """The model should expose all 4 variables after reading a complex report.

    This reproduces the failure pattern from expose-tool-failure-analysis.md:
    the model must call internal__read_report to get the report content,
    then extract labeled sections and emit a JSON block. With complex
    multi-paragraph values, the model tends to call think, describe the
    values in prose, and end its turn without emitting the JSON block.
    """
    runtime = AWLRuntime(real_agent, limits=RuntimeLimits(max_tool_calls=15))

    workflow = WorkflowNode(
        body=[
            TaskNode(
                task_id="extract_decisions",
                goal=(
                    "Read the report named 'pr-analysis-247' using internal__read_report, "
                    "then extract the following labeled sections from the report content "
                    "and expose them as variables. Do NOT summarize — preserve the full "
                    "text of each section exactly as written in the report.\n\n"
                    "Sections to extract:\n"
                    "- NEEDS_CODE_CHANGES (boolean)\n"
                    "- FIX_PLAN (full multi-step plan text)\n"
                    "- COMPANION_REPOS (full list with descriptions)\n"
                    "- PR_COMMENTS_SUMMARY (full reviewer feedback text)"
                ),
                expose=[
                    "needs_code_changes",
                    "fix_plan",
                    "companion_repos",
                    "pr_comments_summary",
                ],
            ),
            IfNode(
                expression="needs_code_changes",
                then_body=[
                    TaskNode(
                        task_id="apply_fixes",
                        goal="Summarize the fix plan: ${fix_plan}",
                    ),
                ],
                else_body=[
                    TaskNode(
                        task_id="skip",
                        goal="Report that no code changes are needed.",
                    ),
                ],
            ),
        ]
    )

    result = await runtime.execute(workflow)
    captured = capsys.readouterr()

    # Core assertion: all 4 variables should have been exposed
    assert "needs_code_changes" in result.variables, f"needs_code_changes not exposed. Output:\n{captured.out}"
    assert (
        result.variables["needs_code_changes"] is not None
    ), f"needs_code_changes is None (expose failed). Output:\n{captured.out}"

    # The @if should have taken the then-branch (apply_fixes)
    assert "apply_fixes" in captured.out, f"apply_fixes task did not run — wrong branch taken. Output:\n{captured.out}"

    # All 4 vars should be non-None
    for var in ["needs_code_changes", "fix_plan", "companion_repos", "pr_comments_summary"]:
        assert (
            result.variables.get(var) is not None
        ), f"{var} is None — expose failed for this variable. Output:\n{captured.out}"


@skip_no_api
@pytest.mark.asyncio
async def test_expose_simple_values_succeeds(real_agent, capsys):
    """Baseline: exposing simple/trivial values should always work.

    This confirms the pattern from the report: simple values (false, short
    strings) are exposed reliably, establishing the contrast with complex values.
    """
    runtime = AWLRuntime(real_agent, limits=RuntimeLimits(max_tool_calls=10))

    workflow = WorkflowNode(
        body=[
            TaskNode(
                task_id="simple_extract",
                goal=(
                    "Answer these questions and expose the results:\n"
                    "- is_urgent: false (this is not urgent)\n"
                    "- category: 'documentation'\n"
                    "- item_count: 0"
                ),
                expose=["is_urgent", "category", "item_count"],
            ),
        ]
    )

    result = await runtime.execute(workflow)

    # Simple values should always be exposed successfully
    for var in ["is_urgent", "category", "item_count"]:
        assert var in result.variables, f"{var} not exposed"
        assert result.variables[var] is not None, f"{var} is None"
